language: php


php:
  - 5.4

mysql:
  database: drupal
  username: root
  encoding: utf8

before_script:
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart
  # Install drush.
  - pear channel-discover pear.drush.org
  - pear install drush/drush
  - phpenv rehash
  - drush dl drupal --destination=. --drupal-project-rename=drupal
  - cd drupal
  - sudo chmod -R 777 sites/all/modules
  - /usr/bin/env PHP_OPTIONS="-d sendmail_path=$(which true)" drush si --db-url=mysql://root:@127.0.0.1/drupal --account-name=admin --account-pass=test --site-mail=webmaster@roomify.us --site-name="test" --yes
  - drush cc all --yes


script:
  - curl http://127.0.0.1/drupal/

after_failure:
  # Output server log.
  - sudo cat /var/log/apache2/access.log
  - sudo cat /var/log/apache2/error.log
